permissions:
  contents: write
name: Deploy
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    name: Deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#        os: [ ubuntu-latest, [ macOS, X64], [ macOS, ARM64 ] ]
        os: [ ubuntu-20.04, macos-12, macos-14 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
           python-version: '3.11'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: iMolpro-github
      - name: Build
        run: |
          if [ -z "${CONDA_EXE}" ]; then export CONDA_EXE=$(readlink -f $(which conda)) ; fi
          echo github.ref ${{ github.ref }}
          conda config --set solver libmamba
          . $(dirname $CONDA_EXE)/../etc/profile.d/conda.sh
          conda activate iMolpro-github
          bash build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*bz2
            dist/*dmg
  deploy-windows:
    name:  Deploy on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: iMolpro-github
          auto-activate-base: false
      - name: Build
        shell: pwsh
        run: .\build.ps1
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            iMolpro*.exe

      - name: Delete old latest releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tag_pattern: 'latest*'
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
