name: Tag latest

on:
  push:
    branches:
      - 'master'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
      - uses: qoomon/actions--access-token@v3
        id: access-token
        with:
#          repository: <TARGET_REPO>
          permissions: |
            contents: write
            actions: write
      - name: Checkout branch "master"
        uses: actions/checkout@v4
        with:
          ref: 'master'
          token: ${{ steps.access-token.outputs.token }}
      - name: tag
        id: tag
        run: |
          sha_short=$(git rev-parse --short HEAD)
          date=$(date +'%Y-%m-%d')
          tag=latest-${date}-${sha_short}
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          git tag ${tag}
          git push --tags

    outputs:
      tag_name: ${{ steps.tag.outputs.tag }}

  clean:
    name: Clean obsolete latest
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Delete old latest releases
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          keep_latest: 1
          delete_tag_pattern: 'latest*'
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
